version: "3"
services:
  detect:
    image: cristiando0902/ncnn_ubuntu:1.0
    command: bash
    # command: bash /source/init.sh
    volumes: 
      - ./:/source
    container_name: "face-ncnn"
    tty: true