version: "3"
services:
  detect:
    image: cristiando0902/worker:1.0
    command: bash
    # command: bash /source/init.sh
    volumes: 
      - ./:/source
      - ./models:/models
      - ./stores:/stores
    container_name: "detect"
    tty: true
